# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160212184438 on 2016-02-17 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.IntegerField()),
                ('title', models.CharField(max_length=247)),
                ('keyword', models.CharField(max_length=249, unique=True)),
            ],
            options={
                'db_table': 'bb_keywords',
                'managed': False,
            },
        ),
    ]
