# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160212184438 on 2016-02-17 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_authuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='linkedkeywords',
            table='linked_keywords',
        ),
    ]
